sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gbgq8AYPO9xdRvjbe+eYeJBrMZPHlFPyXUdRSKWSWJntgWGD0i4ODQRvRsNj4s6Z/RvT+HuNh03L17/eT/FsDFRupHJWUqcdXpmEQy5k07rglPkSNsMI1BL2hL9j65ur+9fSMxEgapGjysEcpeIKvBUqxuuSdr/2Wj/ZnR009B0+OdDNRU/RcFmvoFN0CmqBER3Aira/a38DfkOxJjNlrLl1hS+mI7hHL2gpuAsiDwkE74qIjHLjcqDiOAi1FOVevwIdWj3KjjgBfIlNBfSgK/IshciO1DDasYScmKzYLgA3M8GXtN+z4tONf4soZKPHL6UcSt42PvmA0nTwNKTNdLAdMubfsr3rgv+ol0+nzK8Mv+t1e1pP7qo8PRf42SJpM8AVFMgMwWP6EthbR1W6A6/WUVqX9OtbCxrkh+PK66UNX+OO+FLkJfVSV1THmx3++QxVBzHvj3dkfx7q9NVbdnAogD5JXkmp1Fna6gYeJs5T4jv1Z2f+91Bz9mDQ6FvExgeaYNE3dBTs9hVQsTh/mYm8i1YYjYd+k46ZapcPFJpOl/n8sVA7CtIi5k8zq8cEMBmjUvB11DZ4Opxls1dJFOiS+tKkW4Rk80ai6ym9hena9Q7woc8Vq/oaBE+Uj5Ag7lgvCf2nxVJMj+NPgGQ6yuXFdNFnbCJ8xz9HqGvbOWY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Aesop-s-Fables--a-new-translation_11339
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy